language: rust

cache: cargo

sudo: false

script:
  - cargo build --release --example blinking
  - cd rp-sys
  - cargo build --release --example blinking
  - exit $(diff <(grep 'pub fn ' src/) <(grep 'pub fn ' mock/src/ | sed 's/^mock\///') | wc -l)
