[package]
name = "redpitaya"
description = "Crate to manipulate redpitaya"
license = "MIT"
version = "0.3.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
repository = "https://github.com/sanpii/redpitaya-rs.git"
documentation = "https://docs.rs/redpitaya/"
keywords = ["redpitaya"]
categories = ["api-bindings", "hardware-support"]

[dependencies]
libc = "0.2"

[dependencies.rp-sys]
path = "rp-sys"
version = "0.6"

[badges]
travis-ci = { repository = "sanpii/redpitaya-rs" }
