[package]
name = "redpitaya"
description = "Crate to manipulate redpitaya"
license = "MIT"
version = "0.26.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
repository = "https://github.com/yellow-pitaya/api.git"
documentation = "https://docs.rs/redpitaya/"
keywords = ["redpitaya"]
categories = ["api-bindings", "hardware-support"]
edition = "2018"

[dependencies]
libc = "0.2"

[dependencies.rp-sys]
path = "rp-sys"
version = "0.25"
optional = true

[dependencies.rp-mock]
path = "rp-mock"
version = "0.1"
optional = true

[features]
default = ["rp-sys"]
mock = ["rp-mock"]

[badges]
travis-ci = { repository = "yellow-pitaya/api" }
gitlab = { repository = "yellow-pitaya/api" }
