[package]
name = "rp-sys"
version = "0.8.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
description = "FFI bindings to redpitaya API"
repository = "https://github.com/sanpii/redpitaya-rs.git"
documentation = "https://docs.rs/rp-sys"
keywords = ["redpitaya"]
license = "MIT"
build = "build.rs"
links = "rp"
categories = ["external-ffi-bindings", "hardware-support"]

[dependencies]
libc="0.2.0"

[badges]
travis-ci = { repository = "sanpii/redpitaya-rs" }
gitlab = { repository = "https://gitlab.com/sanpi/redpitaya-rs" }
